services:

  flask:
    build:
      context: ./flask
    command: python -u app.py
    volumes:
      - ./flask:/app
    ports: 
      - "5002:5002"
    depends_on:
      - postgres_db
    environment:
      - FLASK_ENV=development

  react:
    build:
      context: ./react
    volumes:
      - ./react:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR=ture
    depends_on:
      - flask

  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: financeDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:

networks:
  default:
    driver: bridge