"""added Market Cap column to Stocks table

Revision ID: 62c2f90cf937
Revises: 
Create Date: 2024-08-21 15:34:09.430461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62c2f90cf937'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('indices_price_key', 'indices', type_='unique')
    op.drop_constraint('indices_open_key', 'indices', type_='unique')
    op.drop_constraint('indices_prev_close_key', 'indices', type_='unique')
    op.drop_constraint('indices_dayRange_key', 'indices', type_='unique')
    op.drop_constraint('indices_yearLow_key', 'indices', type_='unique')
    op.drop_constraint('indices_yearHigh_key', 'indices', type_='unique')
    op.drop_constraint('indices_volume_key', 'indices', type_='unique')
    op.drop_constraint('indices_changePercentage_key', 'indices', type_='unique')
    
    # Alter columns to be nullable
    op.alter_column('indices', 'name', existing_type=sa.VARCHAR(length=80), nullable=True)
    op.alter_column('indices', 'price', existing_type=sa.FLOAT(), nullable=True)
    op.alter_column('indices', 'open', existing_type=sa.FLOAT(), nullable=True)
    op.alter_column('indices', 'prev_close', existing_type=sa.FLOAT(), nullable=True)
    op.alter_column('indices', 'dayRange', existing_type=sa.FLOAT(), nullable=True)
    op.alter_column('indices', 'yearLow', existing_type=sa.FLOAT(), nullable=True)
    op.alter_column('indices', 'yearHigh', existing_type=sa.FLOAT(), nullable=True)
    op.alter_column('indices', 'volume', existing_type=sa.BigInteger(), nullable=True)
    op.alter_column('indices', 'changePercentage', existing_type=sa.FLOAT(), nullable=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('indices_changePercentage_key', 'indices', ['changePercentage'])
    op.create_unique_constraint('indices_volume_key', 'indices', ['volume'])
    op.create_unique_constraint('indices_yearHigh_key', 'indices', ['yearHigh'])
    op.create_unique_constraint('indices_yearLow_key', 'indices', ['yearLow'])
    op.create_unique_constraint('indices_dayRange_key', 'indices', ['dayRange'])
    op.create_unique_constraint('indices_prev_close_key', 'indices', ['prev_close'])
    op.create_unique_constraint('indices_open_key', 'indices', ['open'])
    op.create_unique_constraint('indices_price_key', 'indices', ['price'])
    
    # Revert columns to non-nullable
    op.alter_column('indices', 'changePercentage', existing_type=sa.FLOAT(), nullable=False)
    op.alter_column('indices', 'volume', existing_type=sa.BigInteger(), nullable=False)
    op.alter_column('indices', 'yearHigh', existing_type=sa.FLOAT(), nullable=False)
    op.alter_column('indices', 'yearLow', existing_type=sa.FLOAT(), nullable=False)
    op.alter_column('indices', 'dayRange', existing_type=sa.FLOAT(), nullable=False)
    op.alter_column('indices', 'prev_close', existing_type=sa.FLOAT(), nullable=False)
    op.alter_column('indices', 'open', existing_type=sa.FLOAT(), nullable=False)
    op.alter_column('indices', 'price', existing_type=sa.FLOAT(), nullable=False)
    op.alter_column('indices', 'name', existing_type=sa.VARCHAR(length=80), nullable=False)
    
    # ### end Alembic commands ###