"""added Market Cap column to Stocks table

Revision ID: 62c2f90cf937
Revises: 
Create Date: 2024-08-21 15:34:09.430461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62c2f90cf937'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Market_Cap', sa.Integer(), nullable=False))
        op.execute('ALTER TABLE stocks ALTER COLUMN price TYPE INTEGER USING (price::INTEGER)')
        batch_op.create_unique_constraint(None, ['Market_Cap'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('price',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('Market_Cap')

    # ### end Alembic commands ###
